import type { BookContent } from '../../types/book/content'
import {
  ALCALDE_PHOTOS,
  GENTE_PHOTOS,
  V_PLAYA_TURQUESA,
  V_LAGUNA_ALALAY,
  V_TERMINAL_BUSES,
  V_FEXCO_ARENA,
  V_PERMISO_VIAJE,
  V_CLINICA_VETERINARIA,
} from './media-paths'

export const bookContent: BookContent = {
  city: 'Cochabamba',
  badge: 'Bolivia',
  tagline: 'La Ciudad de la Eterna Primavera',
  intro:
    'Descubre la riqueza cultural, los sabores ancestrales y los paisajes que hacen de Cochabamba un destino único en el corazón de Sudamérica.',
  year: '2026',
  title: 'Cocha la mejor ciudad de Bolivia',
  subtitle: 'Álbum de fotos',
  cover: {
    image: '/images/portada.png',
  },

  sections: [
    {
      id: 'presentacion',
      title: 'Presentación del alcalde',
      description: 'Relato emotivo y foto traje formal',
      items: [
        { text: 'Manfred Reyes Villa', image: ALCALDE_PHOTOS[0] },
        { text: 'El alcalde', image: ALCALDE_PHOTOS[1] },
        { text: 'Formal', image: ALCALDE_PHOTOS[2] },
      ],
    },
    {
      id: 'crecimiento',
      title: 'Cómo ha crecido Cochabamba: de una ciudad de ayer a una ciudad que mira al futuro',
      description:
        'Las fotografías cuentan aquello que muchas veces las palabras no pueden explicar: el paso del tiempo y la transformación de una ciudad. Cochabamba conserva en sus calles, plazas, barrios y edificios la memoria de lo que fue, pero también muestra, en cada avenida y espacio renovado, el impulso de una ciudad que comenzó a proyectarse hacia el futuro.',
      items: [
        { text: 'Calles', image: GENTE_PHOTOS[0] },
        { text: 'Casas', image: GENTE_PHOTOS[1] },
        { text: 'Gente', image: GENTE_PHOTOS[2] },
        { text: 'Ciudad colonial', image: GENTE_PHOTOS[3] },
        { text: 'Iglesias', image: GENTE_PHOTOS[4] },
      ],
    },
    {
      id: 'nueva-cochabamba',
      title: 'El inicio de una nueva Cochabamba',
      description:
        'Manfred Reyes Villa, Visión moderna de ciudad y planificación urbana. Con la llegada de una nueva etapa de gestión municipal, Cochabamba comenzó a plantearse un desafío distinto: dejar de responder únicamente a las necesidades del presente y empezar a planificar la ciudad que sus habitantes necesitarían en el futuro.',
      items: [],
    },
    {
      id: 'obras-memorias',
      title: 'Las obras son memorias',
      description:
        'La transformación de Cochabamba durante los años 90\' no puede entenderse únicamente a través de una lista de obras. Cada avenida, parque, puente, plaza y programa social representa una parte de la historia de una ciudad que comenzaba a mirar más allá de su presente. Cada proyecto refleja una época en la que Cochabamba comenzó a imaginarse como una ciudad moderna, integrada y con vocación de futuro.',
      items: [],
    },
    {
      id: 'puentes-pasos-desnivel',
      title: 'Pioneros en la implementación de pasos a desnivel y puentes',
      items: [
        { text: 'Puente Cala Cala 1993', image: ALCALDE_PHOTOS[0] },
        { text: 'Puente Los Andes entre las serranías de Cerro Verde y San Miguel 1993', image: ALCALDE_PHOTOS[1] },
        { text: 'Puente Kyllmann 1994', image: ALCALDE_PHOTOS[2] },
        { text: 'Viaducto 1996', image: ALCALDE_PHOTOS[3] },
        { text: 'Puente Antezana 1996', image: ALCALDE_PHOTOS[4] },
        { text: 'Puente Muyurina 2004', image: ALCALDE_PHOTOS[5] },
      ],
    },
    {
      id: 'conectividad',
      title: 'La conectividad: motor del crecimiento urbano',
      description: 'Asfalto y Pavimento rígido',
      items: [
        { text: 'Suecia' },
        { text: 'Cap. Ustariz' },
        { text: 'D\'Orbigni' },
        { text: 'Melchor Pérez' },
        { text: 'Independencia' },
        { text: 'Petrolera' },
        { text: 'Gabriel René Moreno' },
        { text: 'Beijing' },
      ],
    },
    {
      id: 'ciudad-jardin',
      title: 'Ciudad Jardín: Áreas verdes y parques',
      items: [
        { text: 'Parque de educación vial', image: GENTE_PHOTOS[5] },
        { text: 'Parque del niño', image: GENTE_PHOTOS[6] },
        { text: 'Parque Mariscal Santa Cruz 1998', image: GENTE_PHOTOS[7] },
        { text: 'Parque Kanata', image: GENTE_PHOTOS[8] },
        { text: 'Parque San Pedro', image: GENTE_PHOTOS[9] },
        { text: 'Plaza 14 de septiembre', image: GENTE_PHOTOS[10] },
        { text: 'Plaza Colón', image: GENTE_PHOTOS[11] },
        { text: 'Plaza Recoleta', image: GENTE_PHOTOS[12] },
        { text: 'Plaza Quintanilla', image: GENTE_PHOTOS[13] },
        { text: 'Plaza de las banderas', image: GENTE_PHOTOS[14] },
      ],
    },
    {
      id: 'desayuno-escolar',
      title: 'Pioneros en la implementación del Desayuno Escolar en Bolivia',
      description: '1994, logrando que se instituya a nivel nacional en beneficio de miles de estudiantes.',
      items: [{ text: 'Desayuno Escolar 1994', image: ALCALDE_PHOTOS[6] }],
    },
    {
      id: 'iluminacion',
      title: 'Iluminación',
      description: 'Cambio de luces de mercurio a sodio 1994',
      items: [],
    },
    {
      id: 'misicuni',
      title: 'Misicuni',
      description: 'El sueño del agua que Cochabamba no dejó de perseguir',
      items: [],
    },
    {
      id: 'defensorias',
      title: 'Defensorías Municipales de la Niñez y Adolescencia',
      description: 'Siendo Cochabamba identificada como pionera en este proceso 1997',
      items: [],
    },
    {
      id: 'cristo-concordia',
      title: 'Cristo de la Concordia',
      description: 'Un símbolo que se convirtió en el rostro de Cochabamba 1994',
      items: [{ text: 'Cristo de la Concordia 1994', image: ALCALDE_PHOTOS[0] }],
    },
    {
      id: 'teleferico',
      title: 'Primer Teleférico de Bolivia',
      description: '1999',
      items: [{ text: 'Primer Teleférico de Bolivia 1999', image: ALCALDE_PHOTOS[1] }],
    },
    {
      id: 'peaton-ciclista',
      title: 'Día del peatón y del ciclista',
      description: 'Iniciativa impulsada por Manfred Reyes Villa 1999 / Ciclovía 1999',
      items: [{ text: 'Ciclovía 1999', image: GENTE_PHOTOS[0] }],
    },
    {
      id: 'ciudad-suenos',
      title: 'Cuando una ciudad vuelve a soñar en grande, las obras se convierten en el camino hacia el futuro',
      description:
        'En 2021, Cochabamba inició una nueva etapa de transformación urbana y social. La experiencia acumulada y una visión de ciudad moderna volvieron a encontrarse con las necesidades de una población que exigía soluciones concretas. Agua, salud, educación, movilidad, medio ambiente, cultura, tecnología, deporte y desarrollo productivo se convirtieron en parte de una agenda municipal orientada a recuperar espacios, modernizar servicios y llevar obras a los distintos distritos.',
      items: [],
    },
    {
      id: 'salud-calidad',
      title: 'Salud de calidad',
      description:
        'La emergencia sanitaria dejó una enseñanza: la infraestructura y el equipamiento médico pueden marcar la diferencia entre la vida y la muerte. Fortalecer el sistema de salud fue primordial; se priorizó la implementación de la primera planta criogénica municipal de oxígeno, se gestionó la entrega de unidades de terapia intensiva (UTI), equipamiento hospitalario y una red municipal de ambulancias destinadas a salvar vidas.',
      items: [
        { text: 'Primera Planta Criogénica Municipal de Oxígeno - ubicada en el Hospital del Norte', image: ALCALDE_PHOTOS[2] },
        { text: 'Unidades de terapia intensiva - Hospital del Norte y Sud' },
        { text: 'Red Municipal de Ambulancias / línea gratuita 162' },
        { text: 'Equipamiento hospitales: Tomógrafo - Hospital Cochabamba' },
        { text: 'Neonatología - Hospital Cochabamba' },
        { text: 'Torre Laparoscópica - Hospital del Sud' },
        { text: 'Mamógrafo - Hospital del Norte' },
        { text: 'Fichaje Virtual - INNOVA' },
        { text: 'Salud Sobre Ruedas (atención médica gratuita)' },
        { text: 'Campañas de Cirugías gratuitas de manos y pies "Manitos Arriba"' },
        { text: 'Centro de Salud Ambulatorio "Gloria" D.9' },
        { text: 'Centro de Salud Integral Villa Israel D.9' },
        { text: 'Clínica veterinaria y centro municipal de Rehabilitación y Adiestramiento Canino - Zona Chimba', video: V_CLINICA_VETERINARIA },
      ],
    },
    {
      id: 'agua-potable',
      title: 'Cobertura de agua potable: deuda social',
      description:
        'Garantizar agua significa garantizar salud, dignidad y oportunidades. La ampliación de redes, sistemas de abastecimiento, colectores y proyectos de saneamiento se convirtió en uno de los principales desafíos de la gestión municipal.',
      items: [
        { text: 'Planta de tratamiento de aguas residuales de Albarrancho. La primera de Bolivia y una de las más grandes de Latinoamérica.', image: ALCALDE_PHOTOS[3] },
        { text: 'Renovación sistema de agua potable centro de la ciudad' },
        { text: 'Cobertura 96% agua potable' },
        { text: 'Ampliaciones y renovaciones de servicios básicos (Agua Potable y Alcantarillado Sanitario)' },
        { text: 'Emisario Sud Este' },
        { text: 'Hidrantes' },
        { text: 'Colector Av. 6 de agosto' },
        { text: 'Colector Av. Ayacucho' },
      ],
    },
    {
      id: 'ciudad-jardin-recracion',
      title: 'Cochabamba, Ciudad Jardín: recreación y encuentro',
      description:
        'La Ciudad Jardín y de la Eterna Primavera renueva su esencia con plazas, parques y espacios llenos de color y vegetación. Hoy, ese legado se proyecta hacia el futuro con la recuperación de áreas verdes, la creación de nuevos espacios de encuentro y la implementación del Plan Maestro de Forestación y Reforestación Municipal, Bosques Urbanos y Arborizaci\u00f3n, consolidando a la ciudad como un verdadero pulmón ecológico para las nuevas generaciones.',
      items: [
        { text: 'Parque de la Integración - atractivo recreacional con piscina, plaza de comidas y juegos ubicado en el D.9 zona sur', image: GENTE_PHOTOS[1] },
        { text: 'Plaza Julio León Prado D.10', image: GENTE_PHOTOS[2] },
        { text: 'Prado Av. Humberto Asón' },
        { text: 'La "Casa de Piedra", un nuevo paraje turístico en la llajta' },
        { text: 'Jardineras centrales y áreas verdes (emoticones, mariposas y pavos)' },
        { text: 'Parques (Familia, Vial, El pulpo, Autonomía, Bicentenario, Oblitas, Kanata, Mariscal Santa Cruz)' },
        { text: 'Bosques urbanos (Fidel Anze, Lincoln, Excombatientes, Demetrio Canelas, Esferas Florales)', image: GENTE_PHOTOS[3] },
        { text: 'Remozado y mejoramiento fuentes plaza de las Banderas y Recoleta', image: GENTE_PHOTOS[4] },
      ],
    },
    {
      id: 'futuro-ecologico',
      title: 'Un compromiso con el futuro ecológico',
      description:
        'La llajta avanza hacia un futuro más verde, limpio y sostenible. La protección del medio ambiente se ha convertido en un compromiso con las presentes y futuras generaciones, impulsando acciones para recuperar áreas naturales, mejorar la calidad del aire, promover una movilidad sostenible y fortalecer la conciencia ambiental. Porque construir una mejor ciudad no solo significa levantar grandes obras, sino también proteger el agua, cuidar el aire, recuperar la naturaleza y devolverle a Cochabamba el verde que siempre la ha caracterizado.',
      items: [],
    },
    {
      id: 'cocha-sostenible',
      title: 'Cocha, Ciudad Sostenible',
      items: [
        { text: 'Cierre definitivo de ladrilleras' },
        { text: 'Plan Maestro de Ciclovías (puente metálico, puentes cajón, micropavimento rojo)', image: ALCALDE_PHOTOS[4] },
        { text: 'Centro de Inspección Vehicular Ambiental (CIVAM)' },
        { text: 'Centro de Educación Ambiental Municipal (CEAM)' },
        { text: 'Rompiendo Aceras - Iniciativa de arborización urbana de la ciudad, diseñada para romper el cemento de las veredas del centro histórico y plantar árboles en su lugar.' },
        { text: 'MANFRED REYES VILLA "EMBAJADOR DE LA ORGANIZACIÓN MUNDIAL CIUDADES SOSTENIBLES 2026" PARÍS - FRANCIA' },
      ],
    },
    {
      id: 'espejos-agua',
      title: 'Nuestros espejos de agua',
      description:
        'Cochabamba vuelve a mirar hacia sus espejos de agua como espacios de vida, encuentro y recreación. La recuperación de la Laguna Alalay y Coña Coña se convirtió en uno de los grandes desafíos ambientales de la ciudad. Las labores de dragado y tratamiento en Alalay permitieron avanzar en la recuperación del espejo de agua y del ecosistema asociado. Cumpliendo el compromiso de devolver a la ciudad espacios naturales renovados, proteger sus ecosistemas y generar nuevos lugares para disfrutar en familia.',
      items: [
        { text: 'Dragado y recuperación de la Laguna Alalay', video: V_LAGUNA_ALALAY },
        { text: 'Complejo Recreacional Coña Coña D.4 - espacio público de recreación y turismo con playa artificial.', video: V_PLAYA_TURQUESA },
      ],
    },
    {
      id: 'educacion-integral',
      title: 'Educación integral',
      description:
        'El gobierno municipal ha destinado importantes esfuerzos a la construcción, ampliación y mejoramiento de infraestructuras educativas, beneficiando a miles de estudiantes con ambientes dignos, modernos y adecuados para aprender. Cada aula renovada y cada espacio equipado representan una apuesta por el talento, los sueños y las capacidades de las nuevas generaciones, brindándoles mejores herramientas para construir el futuro de nuestra ciudad y de Bolivia.',
      items: [
        { text: 'Construcción de nuevas infraestructuras educativas', image: ALCALDE_PHOTOS[5] },
        { text: 'U.E. BUENAS NUEVAS A-B D.6' },
        { text: 'U.E. INNOVA BELÉN D.15' },
        { text: 'U.E. SAN PEDRO SECUNDARIA D.9' },
        { text: 'U.E. RENÉ BARRIENTOS "B" D.8' },
        { text: 'U.E. SAN PEDRITO - INICIAL Y PRIMARIA D.9' },
        { text: 'U.E. OSCAR ROJAS CABALLERO D.5' },
        { text: 'U.E. CLUB DE LEONES - D.2' },
        { text: 'U.E. TAQUIÑA A-B D.13' },
        { text: 'U.E. 27 DE MAYO D.10' },
        { text: 'U.E. GENOVEVA RÍOS D.2' },
        { text: 'U.E. ÁNGEL HONORATO SALAZAR D.5' },
        { text: 'U.E. BOLIVIA "B" D.9' },
        { text: 'Ampliación y mejoramiento de infraestructuras educativas' },
        { text: 'Alimentación Complementaria Escolar, desde el primer día de clases' },
        { text: 'Entrega de mobiliario educativo' },
        { text: 'Internet gratuito para Unidades Educativas (500 km de fibra óptica propia)' },
      ],
    },
    {
      id: 'infraestructura-vial',
      title: 'Cochabamba conectada: infraestructura vial para una ciudad que avanza',
      description:
        'La infraestructura vial volvió a ocupar un lugar central en la transformación de Cochabamba. Puentes, distribuidores, pavimento rígido, asfaltos, recarpetados y nuevas conexiones buscan responder a una ciudad que crece y necesita desplazarse mejor.',
      items: [
        { text: 'Distribuidor Quintanilla', image: ALCALDE_PHOTOS[6] },
        { text: 'Distribuidor Av. Perú y Av. Blanco Galindo', image: ALCALDE_PHOTOS[0] },
        { text: 'Reposición de la plataforma del "Puente caído" de la Av. 6 de agosto e Independencia' },
        { text: 'Pavimento rígido Av. París D.8' },
        { text: 'Pavimento rígido Av. Pisiga D.14' },
        { text: 'Pavimento rígido Av. Segunda Circunvalación' },
        { text: 'Pavimento rígido Av. Humberto Asón D.8' },
        { text: 'Pavimento rígido Av. Costanera del Sur D.9' },
        { text: 'Pavimento rígido Av. Segunda D.3' },
        { text: 'Pavimento rígido Av. De la Integración D.9' },
        { text: 'Micropavimento' },
        { text: 'Asfalto Av. Circunvalación oeste - Parque Bicentenario' },
        { text: 'Recarpetados avenidas estructurantes: Villarroel, Santa Cruz, Juana Azurduy, Pando' },
        { text: 'Reconfiguración rotonda Muyurina D.11' },
        { text: 'Túnel de la Integración entre Cercado (D.7) y Sacaba', image: ALCALDE_PHOTOS[1] },
        { text: 'Instalación de postes dodecágones en principales avenidas' },
      ],
    },
    {
      id: 'vanguardia-progreso',
      title: 'Cochabamba a la vanguardia del progreso',
      description:
        'La ciudad avanza con soluciones innovadoras que mejoran la vida cotidiana, recuperan y hacen más accesibles los espacios públicos, optimizan los servicios y fortalecen su infraestructura. Contenedores soterrados, aceras inclusivas, nuevas vías de acceso, iluminación LED y modernos espacios municipales reflejan una ciudad que se renueva, incorpora tecnología y se prepara para los desafíos del futuro.',
      items: [
        { text: 'Contenedores Soterrados - Sistema moderno de recolección de basura bajo tierra que permite a los vecinos botar sus residuos a cualquier hora, obra pionera en Bolivia.' },
        { text: 'Cambio de aceras inclusivas en el Casco Viejo' },
        { text: 'Renovación de Alumbrado Público a Tecnología LED' },
        { text: 'Construcción del Edificio Municipal D.10', image: ALCALDE_PHOTOS[2] },
        { text: 'Accesos a la Nueva Terminal de Buses (D.5 y D.9)', video: V_TERMINAL_BUSES },
      ],
    },
    {
      id: 'alianzas-publico-privadas',
      title: 'Pioneros en alianzas público privadas',
      description:
        'Cuando las ideas se suman, el desarrollo multiplica su fuerza. El municipio abre nuevas oportunidades a través de alianzas que unen la visión pública con la iniciativa privada, convirtiendo proyectos en espacios para el encuentro, la inversión, el entretenimiento y el desarrollo económico. La transformación de la FEXCO y la incorporación de nuevos escenarios reflejan una nueva forma de impulsar infraestructura y generar oportunidades para la ciudad.',
      items: [
        { text: 'Feria Exposición Internacional de Cochabamba (FEXCO)', image: ALCALDE_PHOTOS[3] },
        { text: 'Pórtico de acceso principal' },
        { text: 'Pabellón KANATA' },
        { text: 'Pabellón del Emprendedor y artesanos' },
        { text: 'Ampliación Plaza de Comidas', image: GENTE_PHOTOS[5] },
        { text: 'Fexco Arena', video: V_FEXCO_ARENA },
        { text: 'Auditorio Fexco', image: GENTE_PHOTOS[6] },
        { text: 'Karting' },
        { text: 'Construcción Complejo Deportivo de Pádel (APP)' },
        { text: 'Iluminación camino al Cristo de la Concordia' },
        { text: 'Jardín Botánico - Destino nacional' },
        { text: 'Café de experiencia Casona Santiváñez' },
        { text: 'Café de experiencia Teatro Achá' },
        { text: 'Restaurante Temático Casona Mayorazgo' },
        { text: 'Restaurante Casa de Piedra' },
        { text: 'Tirolesa en la serranía de San Pedro' },
        { text: 'Parque de Diversiones FEXCO (Montaña rusa y juegos mecánicos)' },
        { text: 'Hotel para mascotas y horno crematorio' },
      ],
    },
    {
      id: 'destino-turistico',
      title: 'Destino turístico nacional: Cochabamba se visita, se vive',
      description:
        'La ciudad de la eterna primavera cautiva con un clima privilegiado, paisajes que invitan a quedarse, parques y espacios que respiran naturaleza, y una gastronomía que convierte cada plato en parte de su identidad. Pero su mayor atractivo está en su gente: amable, trabajadora y orgullosa de sus raíces. Entre sabores, tradiciones, montañas, cultura y la calidez de su gente, la Llajta se descubre con los sentidos y se queda en el corazón. Porque Cochabamba es una experiencia que se vive, se disfruta y siempre invita a volver.',
      items: [
        { text: '14 Estaciones del Viacrucis, Pórtico de ingreso y renovación de 1.400 escalinatas' },
        { text: 'Restaurante Patrimonio, espacio turístico y gastronómico' },
        { text: 'Apoyo al Evento Madness' },
        { text: 'Carnaval de la Concordia' },
        { text: 'Cochabamba, Ciudad de la Navidad' },
        { text: 'Feria de la Chicha y el Chicharrón' },
        { text: 'Pasaje Portales' },
        { text: 'Casonas' },
        { text: 'Coronilla' },
        { text: 'Gastronomía' },
        { text: 'Leuquepampa - miradores' },
        { text: 'Tunari' },
      ],
    },
    {
      id: 'ciudad-inteligente',
      title: 'Cochabamba, primera ciudad inteligente de Bolivia',
      description:
        'La tecnología se convierte en servicio cuando está al alcance de todos, avanza hacia una nueva forma de vivir y gestionar la ciudad, incorporando innovación, conectividad y herramientas digitales para hacer más ágiles los servicios municipales y acercarlos a la población. La digitalización de trámites, pagos QR, internet gratuito y una red propia de 500 kilómetros de fibra óptica conectan escuelas, centros de salud, plazas y espacios públicos. A esta transformación se suma el impulso al talento tecnológico, construyendo una ciudad más moderna, accesible, eficiente y preparada para el futuro.',
      items: [
        { text: 'Digitalización de los servicios municipales (permisos de viaje, CochaMarket, Visita Cocha)', video: V_PERMISO_VIAJE },
        { text: 'Implementación de pagos QR a través de la app INNOVA' },
        { text: 'Semáforos Inteligentes Sonoros', image: ALCALDE_PHOTOS[4] },
        { text: 'Paneles Led y Señalética inteligente', image: ALCALDE_PHOTOS[5] },
        { text: 'Fortalecimiento del talento tecnológico (Concurso Nacional de Programación "Cocha Somos Innovación" y Feria Tecnológica "Cocha Innova")' },
        { text: 'Centro de Atención Virtual y la línea gratuita 151 para trámites y consultas de la población' },
        { text: 'Internet gratuito y Wifi libre' },
        { text: '500 Km de red de fibra óptica - interconexión de 150 establecimientos educativos' },
        { text: '33 Centros de salud y 50 puntos wifi libre en plazas, áreas verdes, en zonas turísticas e históricas' },
      ],
    },
    {
      id: 'revalorizacion-cultura',
      title: 'Revalorización de la cultura',
      description:
        'Cochabamba guarda en sus calles, monumentos, teatros y en la música de su gente una identidad que atraviesa generaciones. Hoy, esa memoria vuelve a cobrar vida con la preservación de la Torre de la Catedral Metropolitana, la restauración del Teatro Achá y el fortalecimiento de la Orquesta Sinfónica, los Coros y la Banda Municipal. Cada nota, cada escenario y cada piedra restaurada cuentan quiénes somos y de dónde venimos.',
      items: [
        { text: 'Preservación Torre Catedral Metropolitana de Cochabamba', image: ALCALDE_PHOTOS[6] },
        { text: 'Orquesta Sinfónica Municipal', image: GENTE_PHOTOS[0] },
        { text: 'Coro Municipal y Coro de niños' },
        { text: 'Restauración del Teatro Achá - Remodelación de camerinos, cubiertas, nuevas butacas, sonido entre otros' },
        { text: 'Recuperación de espacio para la construcción del Teatro Municipal D.12' },
        { text: 'Banda Municipal' },
      ],
    },
    {
      id: 'semillero-campeones',
      title: 'Semillero de campeones',
      description:
        'Cada deportista comienza con un sueño, una oportunidad y un espacio para entrenar. La alcaldía de Cochabamba impulsa el deporte como una escuela de disciplina, esfuerzo y superación, brindando apoyo a nuestros deportistas, fortaleciendo escenarios deportivos y promoviendo competencias municipales, departamentales, nacionales e internacionales.',
      items: [
        { text: 'Apoyo y fomento al deporte (dotación de material deportivo, trofeos, reconocimientos)' },
        { text: 'Campeonatos internacionales, nacionales, departamentales y municipales' },
        { text: 'Campos deportivos, canchas múltiples, entre otros' },
        { text: 'Juegos Universitarios "Cap. Manfred Reyes Villa"', image: GENTE_PHOTOS[1] },
        { text: 'Escuelas deportivas municipales' },
        { text: 'Reapertura piscina Julio León Prado', image: GENTE_PHOTOS[2] },
        { text: 'Complejo Deportivo Los Pinos Japón D.1' },
      ],
    },
    {
      id: 'proteccion-social',
      title: 'Protección social e inclusión',
      description:
        'Una ciudad que avanza no deja a nadie atrás, fortalece una política social centrada en las personas, promoviendo igualdad de oportunidades, protección y acompañamiento para niñas, niños, adolescentes y familias. Los Centros Infantiles Municipales, Ludotecas, el Parvulario Municipal, la Línea de Atención al Adolescente (LIA) y el Centro de Atención Integral a la Familia (CAIF) representan espacios de cuidado, orientación y apoyo que construyen una sociedad más justa e inclusiva. Porque cuidar, escuchar y acompañar también es transformar la ciudad.',
      items: [
        { text: 'Ley Municipal de Corresponsabilidad en el Trabajo del Cuidado no Remunerado, para la Igualdad de Oportunidades' },
        { text: 'Centros Infantiles municipales' },
        { text: 'Ludotecas municipales' },
        { text: 'Parvulario Edificio Municipal', image: GENTE_PHOTOS[3] },
        { text: 'Línea de Atención al Adolescente (LIA)' },
        { text: 'Centro de Atención Integral a la Familia (CAIF)' },
        { text: 'Línea de emergencias inclusivas (interpretación señas)', image: GENTE_PHOTOS[4] },
      ],
    },
    {
      id: 'cochabamba-productiva',
      title: 'Cochabamba productiva: oportunidades para todos',
      description:
        'La alcaldía de Cochabamba fortalece su vocación productiva apoyando a quienes trabajan la tierra, impulsando la producción agropecuaria y generando espacios dignos para la comercialización y el encuentro. La entrega de semillas, las campañas de sanidad animal y el fortalecimiento de mercados modelo conectan al productor con las familias y dinamizan la economía local.',
      items: [
        { text: 'Impulso a los productores (entrega de semillas, Campaña de desparasitación, vitaminización y sanidad animal en el sector agrario)' },
        { text: '"Noches Creativas" Impulsada por la Ley Municipal N° 1354/2023' },
        { text: '"Cocha se reactiva"' },
        { text: 'Ferias "CochaEmprende"' },
        { text: 'Mercado Integración del Sur' },
        { text: 'Conclusión del Mercado Coraca D.4', image: ALCALDE_PHOTOS[0] },
        { text: 'Construcción Mercado Calatayud', image: ALCALDE_PHOTOS[1] },
        { text: 'Construcción Mercado Papa Paulo', image: ALCALDE_PHOTOS[2] },
        { text: 'Construcción Plaza de Comidas Islas del Sur D.6', image: ALCALDE_PHOTOS[3] },
      ],
    },
    {
      id: 'ciudad-historia',
      title: 'Cochabamba: una ciudad que sigue construyendo su historia',
      description:
        'A través de la regularización del derecho propietario mediante las Resoluciones Administrativas Municipales (RAMs) y el programa "Mi Casa Segura", Cochabamba avanza en la consolidación de hogares con mayor seguridad jurídica y patrimonial. Porque detrás de cada documento existe una historia, un esfuerzo y el sueño de una familia de llamar suyo al lugar que construyó. Regularizar un hogar es también construir tranquilidad y futuro.',
      items: [
        { text: 'Resoluciones Administrativas Municipales (RAMs) - Regularización del Derecho propietario' },
        { text: 'Programa "Mi Casa Segura"' },
      ],
    },
    {
      id: 'cierre',
      title: 'Cierre',
      description:
        'De los primeros puentes a la tecnología; de los parques a los hospitales; del agua a las grandes avenidas, la historia de Cochabamba sigue escribiéndose... Porque una obra puede cambiar un lugar. Pero una visión puede cambiar una ciudad.',
      items: [],
    },
  ],
}
